### ISSUE TITLE
Incorrect failure codes for StatusAuthor 

### ISSUE THREAD

**Issue by jfesler** [nwaples/tacplus#2]
Thanks for sharing your TACACS module.  

When using your module, I was getting back an error code that did not line up with: https://github.com/nwaples/tacplus/blob/9f90d258249bf5cc55490fa92cf5082c6c41742d/packet.go#L81 .  

Digging deeper into your code, and [draft-ietf-opsawg-tacacs-07 section 5.2](https://tools.ietf.org/html/draft-ietf-opsawg-tacacs-07#section-5.2), I found that your FAIL ERROR And FOLLOW constants don't match the IETF draft - I've linked the specific section that shows the correct correct (at least to my reading of the draft) values.

Sadly: _I'm unable to submit a PR due to contractual restrictions._ 😢

**Comment by nwaples** [comment]
Thanks. Its kind of not surprising since I didn't have real hardware to test it against. 
Hopefully I didn't make too many more stupid errors.
